/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerConfig {
	websocket: {
		ip: string;
		port: string;
		password: string;
	};
	rtmp: Server;
	botToken: string;
	checklist: {
		[k: string]: unknown;
	};
}
export interface Server {
	ingest: Settings;
	viewer: Settings;
}
export interface Settings {
	token: string;
	url: string;
}
